apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-s3fs-sipecam-open-data
  namespace: kubeflow
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
